

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    url: jdbc:mysql://127.0.0.1:3306/world?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true
  slave:
    url: jdbc:mysql://127.0.0.1:3307/world?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true


mybatis:
    type-aliases-package: com.antsoft.model #实体类的包
    mapper-locations: classpath:mapper/*.xml #Mapper的xml文件


#mapper:
#    mappers:
#        - com.antsoft.database.BaseMapper
#    not-empty: false
#    identity: MYSQL












